### ISSUE TITLE
KeyError: 'schema'

### ISSUE THREAD

**Issue by datakurre** [deathbeds/jupyterlab-starters#26]
Launching starter without "schema" key in its metadata results in parsing error dialog on JupyterLab (and KeyError: 'schema' on server console).

Not sure if schemaless notebooks is a real use case for notebook starter, but nevertheless i was able to create a one.

**Comment by bollwyvl** [comment]
Thanks! Looking into it!

**Comment by datakurre** [comment]
@bollwyvl Would it make sense to be able (optionally?) to execute the source notebook immediately if it has empty schema? I have mixed feelings to have separate initial schema in metadata and then dynamic schema updated code in cells 🤔

**Comment by bollwyvl** [comment]
> Would it make sense to be able (optionally?) to execute the source notebook immediately if it has empty schema?

The current changes in #29 allows (and tests) for a no-form notebook, if it's _really_ hands-off (can still run `commands` at the end, though). If you don't make a file, there's no indication anything _happened_ though... maybe it needs to do _something_... status bar would be ok, but I don't generally have it on :P. But i think sticking with _no schema, no form_ is pretty solid at present.

> I have mixed feelings to have separate initial schema in metadata and then dynamic schema updated code in cells

Yeah, it's pretty tiered: it goes something like `config` -> `metadata` on-disk -> `metadata` after each execution, with each overwriting the last.

I mostly like the zero-cost, immediately-viewable form (there's a noticeable delay to starting a new kernel). Further, you're then guaranteed to have _some_ structure in the schema, as opposed to having to rewrite it every time. If you really don't want anything, you can create a [`uiSchema` with `ui:readonly`](https://react-jsonschema-form.readthedocs.io/en/latest/form-customization/#read-only-fields) and just show a longer `description`, but still require pressing `|> Start`.

**Comment by datakurre** [comment]
Thanks. That readonly was that part I was missing. Need to learn and try. And I agree that immediate feedback is good reason for initial schema in the notebook.

**Comment by bollwyvl** [comment]
Closed by #29.
