### ISSUE TITLE
Autofocus on input and Ctrl + Enter to press Starter button on starter form

### ISSUE THREAD

**Issue by datakurre** [deathbeds/jupyterlab-starters#27]
Using a starter from keyboard would be nicer if the first input field would have focus after launching a starter and, once the input is completed, some familiar keybinding would invoke the "Start"-button. Not sure if just Enter (like in HTML forms) or Ctrl+Enter (like in Windows dialogs) would be better.

**Comment by bollwyvl** [comment]
First part:
https://react-jsonschema-form.readthedocs.io/en/latest/form-customization/#auto-focus

Second part... yeah... there's a lot of shady business with sidebars and
managing active state. I agree, that would be cool, but at present, it
might execute a code cell in a open notebook or something. Eek.

**Comment by datakurre** [comment]
Ok. Thanks for the auto-focus. That’s good enough. Tab works correctly on the form once the input is focused so the “Start” button is well accessible by kbd.
