### ISSUE TITLE
Schema title and description have too little space between them to be readable

### ISSUE THREAD

**Issue by datakurre** [deathbeds/jupyterlab-starters#31]
![jupyterlab-starters](https://user-images.githubusercontent.com/160447/71645624-8fcd0d80-2ce3-11ea-8f80-fe6c1c70a0b4.png)

Schema

```
    "schema": {                                                                         
     "type": "object",                                                                  
     "description": "Click **START** to launch the tutorial.",                          
     "properties": {},                                                                  
     "required": [],                                                                    
     "title": "# Welcome to Robot Framework on Jupyter"                                 
    },  
```

+ three generated boolean fields with only label

**Comment by datakurre** [comment]
It seems to be possible to add HTML (br or wrapper with style attr) into those markdown processed fields as a workaround.

**Comment by bollwyvl** [comment]
> three generated boolean fields with only label

Is part of the bug? I don't see anything about it in the schema?

> It seems to be possible to add HTML (br or wrapper with style attr) into those markdown processed fields as a workaround.

The backstory for clobbering it was that the default Markdown CSS is set up for narrative documents, not UI, and has _huge_ space around some things like `blockquotes`, `code` and `h*`. Having to do some `br` seems not... bad. 

With CSS (that the starter author doesn't control directly), it's often harder to take away than to add. I've also considered adding [jss](https://cssinjs.org) as a last-ditch styling technique.

**Comment by datakurre** [comment]
The three boolean fields are NOT part of the bug. I simply was unable to export the current schema.

I leave this open for you to decide. For now I can manage with additional markup in the worst looking fields. (Probably just the titles.)

**Comment by datakurre** [comment]
Well, `br` worked well enough, so I'll close this anyway.
