### ISSUE TITLE
Add category and rank properties for placement in launcher

### ISSUE THREAD

**Issue by imcovangent** [deathbeds/jupyterlab-starters#75]
## Elevator Pitch

Wouldn't it be great if you can make new categories for each starter that you have defined? This would mean that each category gets its own header in the launcher and you can structure the starters that you have better.

In addition, would be nice to sort those starters based on `rank` instead of the current default alphabetical sorting.

## Motivation

To better structure the starters in the launcher.

## Design Ideas

Already created a PR for this from my fork.

**Comment by bollwyvl** [comment]
This was fixed in #86, and will be part of #87. Thanks!

**Comment by imcovangent** [comment]
Great to hear it will be part of the new version. Any idea when it will be released?
