### ISSUE TITLE
Add hyperlink type for starter

### ISSUE THREAD

**Issue by imcovangent** [deathbeds/jupyterlab-starters#91]
## What are you trying to do?

I would like to add a new starter type: "hyperlink". This starter is quite simple: you give a link (e.g. https://google.com) and when you click the starter it will go to the link.

Options could be to open the link in a new browser tab or to open the link in an HTML viewer window inside Jupyter Lab.

## How is it done today, and what are the limits of current practice?

This is not part of the current jupyterlab-starters as far as I know.

## What is new in your approach and why do you think it will be successful?

Not sure about the approach actually, any pointers are welcome! Else I will just get started with what I know.

## Who cares? If you are successful, what difference will it make?

You can then add hyperlinks as starters as well. I think it could be nice to refer to, for example, documentation pages, YouTube videos, etc.

## What are the risks?

I'm not aware of any.

## How much will it cost?

Low cost as far as I can see.

## How long will it take?

2 days?

## What are the mid-term and final “exams” to check for success?

Mid-term: add starter with hyperlink that directs to external webpage, either as new browser tab or as new tab in Jupyter Lab UI.

## Final remarks

- Any pointers in the right direction to achieve this?
- Can this be part of the upcoming release 2.0.0 ? If so, when should it be finished?

**Comment by bollwyvl** [comment]
From a categorical perspective: this would be a starter that had _no chance_ of creating a file or other content. So unfortunately, I don't see this as a good match for what starters does... for the most part, it only points at/creates content that is derived from content already deployed, not third-party servers, with the exception being `cookiecutter`, which is rather _special_, and might get dropped anyway, if it weren't so broadly used in the jupyter community.

It's possible that the [`filebrowser:open-url`](https://github.com/jupyterlab/jupyterlab/blob/b09879e20008ec9c6f21f8ec5c6f72a2b1a9c232/packages/filebrowser-extension/src/index.ts#L705) command would do this on an existing starter. that didn't create files.

**Comment by bollwyvl** [comment]
This may meet the needs of opening an arbitrary URL:

https://github.com/trungleduc/jupyter_app_launcher

**Comment by imcovangent** [comment]
Nice, thanks, that's indeed a good option. Also felt indeed that it was a 100% match, but thought you might consider broadening the definition of what a starter is. This new extension will do the job indeed.

Thanks again!
