### ISSUE TITLE
Update to JupyterLab 4

### ISSUE THREAD

**Issue by trungleduc** [deathbeds/jupyterlab-starters#97]
## Elevator Pitch

`@deathbeds/jupyterlab-starters` and `@deathbeds/jupyterlab-rjsf` are very helpful libraries,  since Jlab 4 is around the corner, I want to know if you have a time frame for alphas/betas version which are compatible with JLab 4

## Motivation

We are using `@deathbeds/jupyterlab-rjsf` in our extension https://github.com/QuantStack/jupytercad, which is a JLab 4-only extension. It still works but causes a lot of trouble in resolving the dependencies.

## Design Ideas

N/A

**Comment by bollwyvl** [comment]
Alas, I won't be doing any work against the alpha/beta/rc releases.

Ideally I'd be able to shed all of the custom stuff here, and reuse
something from ***@***.***/ui-components: SchemaForm` with a LabTheme and
an easy to use, well-behaved set of styles. But that's not what we got.

When rjsf5 drops, I'll be doing a release, as I also use this downsteam in
several places, but that effort will still be against 3.5.x, as 3.6rcX
knowingly breaks other things, and I likely won't have time to support
those issues.

**Comment by trungleduc** [comment]
Thank you for the head-up!
